//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoviceCryptoTraderAdvisor.LanguageString {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DynamicElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DynamicElements() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoviceCryptoTraderAdvisor.LanguageString.DynamicElements", typeof(DynamicElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base volume: .
        /// </summary>
        internal static string BaseValuelabel_Text {
            get {
                return ResourceManager.GetString("BaseValuelabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection: Lost.
        /// </summary>
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection: OK.
        /// </summary>
        internal static string ConnectionOk {
            get {
                return ResourceManager.GetString("ConnectionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string DeletePairButton_Text {
            get {
                return ResourceManager.GetString("DeletePairButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Technical Signal.
        /// </summary>
        internal static string GroupBox_TechnicalAnalisis {
            get {
                return ResourceManager.GetString("GroupBox_TechnicalAnalisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на High: .
        /// </summary>
        internal static string HighValuelabel_Text {
            get {
                return ResourceManager.GetString("HighValuelabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 13.
        /// </summary>
        internal static string IndexForRemove {
            get {
                return ResourceManager.GetString("IndexForRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last: .
        /// </summary>
        internal static string LastValuelabel_Text {
            get {
                return ResourceManager.GetString("LastValuelabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low: .
        /// </summary>
        internal static string LowValuelabel_Text {
            get {
                return ResourceManager.GetString("LowValuelabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MACD:.
        /// </summary>
        internal static string MACDlabel_Text {
            get {
                return ResourceManager.GetString("MACDlabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The address .
        /// </summary>
        internal static string MessageBox_Adres {
            get {
                return ResourceManager.GetString("MessageBox_Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart application?.
        /// </summary>
        internal static string MessageBox_ChangeLangQuestion {
            get {
                return ResourceManager.GetString("MessageBox_ChangeLangQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change language.
        /// </summary>
        internal static string MessageBox_ChangeLangTextWindow {
            get {
                return ResourceManager.GetString("MessageBox_ChangeLangTextWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  was copied to the clipboard.
        /// </summary>
        internal static string MessageBox_CopyToClipboard {
            get {
                return ResourceManager.GetString("MessageBox_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save market pairs?.
        /// </summary>
        internal static string MessageBox_SaveQuestion {
            get {
                return ResourceManager.GetString("MessageBox_SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string MessageBox_SaveTextWindow {
            get {
                return ResourceManager.GetString("MessageBox_SaveTextWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not allowed addition more than 200 trade pair.
        /// </summary>
        internal static string MessageBox_Show_MaxPair {
            get {
                return ResourceManager.GetString("MessageBox_Show_MaxPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved successfully....
        /// </summary>
        internal static string MessageBox_Show_SaveMenuButton {
            get {
                return ResourceManager.GetString("MessageBox_Show_SaveMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  wallet was copied to the clipboard.
        /// </summary>
        internal static string MessageBox_WalletToClipboard {
            get {
                return ResourceManager.GetString("MessageBox_WalletToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done.
        /// </summary>
        internal static string ProgressBarDone {
            get {
                return ResourceManager.GetString("ProgressBarDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready.
        /// </summary>
        internal static string ProgressBarReady {
            get {
                return ResourceManager.GetString("ProgressBarReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Worked.
        /// </summary>
        internal static string ProgressBarWorked {
            get {
                return ResourceManager.GetString("ProgressBarWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RSI:.
        /// </summary>
        internal static string RSIlabel_Text {
            get {
                return ResourceManager.GetString("RSIlabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stochastic:.
        /// </summary>
        internal static string Stochlabel_Text {
            get {
                return ResourceManager.GetString("Stochlabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StochRSI:.
        /// </summary>
        internal static string StochRSIlabel_Text {
            get {
                return ResourceManager.GetString("StochRSIlabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume: .
        /// </summary>
        internal static string VolumeValuelabel_Text {
            get {
                return ResourceManager.GetString("VolumeValuelabel_Text", resourceCulture);
            }
        }
    }
}
